### ISSUE TITLE
Maybe generate screenshot from page?

### ISSUE THREAD

**Issue by rogierlommers** [badoux/goscraper#1]
Thanks for your package; I'm using it in my "[greedy app](https://github.com/rogierlommers/greedy)". It would be great if you can add some kind of screenshot generation of the page which is being scraped?

```
type DocumentPreview struct {
  Title             string
  Description string
  Images        []string
  Link             string
  Screenshot []bytes   // rendered screenshot of the scraped url
}
```

**Comment by itsdarrylnorris** [comment]
@rogierlommers , I think this will be an interesting idea. However, it looks like is going to require quite of work. I could be wrong.

Here is a package that looks promising. https://github.com/sensepost/gowitness

**Comment by rogierlommers** [comment]
I will check it out; thanks.
