### ISSUE TITLE
Some URLs result in 'unsupported protocol scheme'

### ISSUE THREAD

**Issue by rogierlommers** [badoux/goscraper#3]
```
package main

import (
	"fmt"
	"log"

	"github.com/badoux/goscraper"
)

func main() {
	s, err := goscraper.Scrape("https://docs.docker.com/engine/admin/host_integration/#examples", 5)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Title : %s\n", s.Preview.Title)

}
```

Gives me the following:

`Get /engine/admin/host_integration/: unsupported protocol scheme ""`

**Comment by badoux** [comment]
Hi.

Thanks for the report.
This bug should be fixed in the latest commit.
(https://github.com/badoux/goscraper/commit/0213ced7087832e81e8892e8d044150cfc153856)

Let me know if it's ok.

**Comment by rogierlommers** [comment]
Thanks; just checked and worked out fine!
